/*
 * MainFrame.java
 *
 * Created on 14.09.2011, 15:27:50
 */
package com.dfki.av.sudplan.ui;

import com.dfki.av.sudplan.camera.AnimatedCamera;
import com.dfki.av.sudplan.camera.SimpleCamera;
import com.dfki.av.sudplan.vis.LayerInfo;
import com.dfki.av.sudplan.vis.VisualizationPanel;
import com.dfki.av.sudplan.vis.WMSHeightUtils;
import com.dfki.av.sudplan.vis.basic.VisCreateTexture;
import com.dfki.av.sudplan.vis.basic.VisPointCloud;
import com.dfki.av.sudplan.vis.core.IVisAlgorithm;
import com.dfki.av.sudplan.vis.spi.VisAlgorithmFactory;
import java.awt.Dimension;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openide.util.Exceptions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Daniel Steffen <daniel.steffen at dfki.de>
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * The logger.
     */
    private static final Logger log = LoggerFactory.getLogger(MainFrame.class);
    /**
     * An array of WMS.
     */
    private static final String[] servers = new String[]{
        "http://serv-2118.kl.dfki.de:8888/geoserver/wms"/*,
        "http://www.wms.nrw.de/geobasis/DOP"*//*
     * ,
     * /*"http://kartor.stockholm.se/bios/wms/app/baggis/web/WMS_STHLM_ORTOFOTO_2009?"/*,
     */
    /*
     * "http://kartor.stockholm.se/bios/wms/app/baggis/web/WMS_STHLM_TATORTSKARTA_RASTER?"
     */

    };
    /**
     * The size of the {@link #wwPanel}.
     */
    private Dimension canvasSize;
    /**
     * The visualization panel wrapping the WorldWind canvas.
     */
    private VisualizationPanel wwPanel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);

        this.canvasSize = new Dimension(1500, 800);
        this.wwPanel = new VisualizationPanel(canvasSize);
        this.wwPanel.setPreferredSize(canvasSize);

        initComponents();

        for (String server : servers) {
            wwPanel.addWMS(server);
        }
        
        // Add LayerTreeComponent to the left split panel.
        JPanel layerTreeComponent = wwPanel.getLayerPanel();
        if(layerTreeComponent != null){
            pLeftPanel.add(layerTreeComponent);
        } else {
            log.debug("No layer tree component available. Could not add the panel.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dGoTo = new javax.swing.JDialog();
        pGoTo = new javax.swing.JPanel();
        lLatitude = new javax.swing.JLabel();
        lLongitude = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        txtLongitude = new javax.swing.JTextField();
        btnCancelGoToDialoag = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        jopAddServer = new javax.swing.JOptionPane();
        dWMSHeight = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pWMSHeight = new javax.swing.JPanel();
        txtServerURL = new javax.swing.JTextField();
        bGoWMSHeight = new javax.swing.JButton();
        cbServerURL = new javax.swing.JComboBox();
        lServerURL = new javax.swing.JLabel();
        pbWMS = new javax.swing.JProgressBar();
        rbTxtServerUrl = new javax.swing.JRadioButton();
        rbCbServerUrl = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        txtRequest = new javax.swing.JTextField();
        pbWMSLayer = new javax.swing.JProgressBar();
        bGoWMSHeight1 = new javax.swing.JButton();
        cLayerList = new javax.swing.JComboBox();
        lOpacity = new javax.swing.JLabel();
        lHeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        bAddWMSHeight = new javax.swing.JButton();
        txtOpacity = new javax.swing.JTextField();
        bCancelWMSHeight = new javax.swing.JButton();
        lMaxEle = new javax.swing.JLabel();
        bgWMS = new javax.swing.ButtonGroup();
        pMain = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pLeftPanel = new javax.swing.JPanel();
        pVisualization = new javax.swing.JPanel();
        mbMain = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miGotoLinz = new javax.swing.JMenuItem();
        miGotoPraque = new javax.swing.JMenuItem();
        miGoToStockhom = new javax.swing.JMenuItem();
        miGotoWuppertal = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        miFullSphere = new javax.swing.JMenuItem();
        miGoto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();
        mLayer = new javax.swing.JMenu();
        mAddLayer = new javax.swing.JMenu();
        miAddGeoTiff = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        miAddShape = new javax.swing.JMenuItem();
        miAddShapeZip = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        miAddWMS = new javax.swing.JMenuItem();
        miAddWMSHeight = new javax.swing.JMenuItem();
        miRemoveAllLayer = new javax.swing.JMenuItem();
        mWizard = new javax.swing.JMenu();
        miWizard = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/dfki/av/sudplan/ui/Bundle"); // NOI18N
        dGoTo.setTitle(bundle.getString("MainFrame.dGoTo.title")); // NOI18N
        dGoTo.setAlwaysOnTop(true);
        dGoTo.setMinimumSize(new java.awt.Dimension(230, 150));
        dGoTo.setResizable(false);

        pGoTo.setMaximumSize(new java.awt.Dimension(200, 100));

        lLatitude.setLabelFor(txtLatitude);
        lLatitude.setText(bundle.getString("MainFrame.lLatitude.text")); // NOI18N

        lLongitude.setLabelFor(txtLongitude);
        lLongitude.setText(bundle.getString("MainFrame.lLongitude.text")); // NOI18N

        txtLatitude.setText(bundle.getString("MainFrame.txtLatitude.text")); // NOI18N

        txtLongitude.setText(bundle.getString("MainFrame.txtLongitude.text")); // NOI18N

        javax.swing.GroupLayout pGoToLayout = new javax.swing.GroupLayout(pGoTo);
        pGoTo.setLayout(pGoToLayout);
        pGoToLayout.setHorizontalGroup(
            pGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGoToLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLongitude)
                    .addComponent(lLatitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        pGoToLayout.setVerticalGroup(
            pGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGoToLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLatitude)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLongitude)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelGoToDialoag.setText(bundle.getString("MainFrame.btnCancelGoToDialoag.text")); // NOI18N
        btnCancelGoToDialoag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelGoToDialoagActionPerformed(evt);
            }
        });

        btnGo.setText(bundle.getString("MainFrame.btnGo.text")); // NOI18N
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dGoToLayout = new javax.swing.GroupLayout(dGoTo.getContentPane());
        dGoTo.getContentPane().setLayout(dGoToLayout);
        dGoToLayout.setHorizontalGroup(
            dGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dGoToLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dGoToLayout.createSequentialGroup()
                        .addComponent(btnGo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelGoToDialoag))
                    .addComponent(pGoTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dGoToLayout.setVerticalGroup(
            dGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dGoToLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pGoTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dGoToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelGoToDialoag)
                    .addComponent(btnGo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dWMSHeight.setTitle(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.dWMSHeight.title")); // NOI18N
        dWMSHeight.setMinimumSize(new java.awt.Dimension(720, 325));
        dWMSHeight.setResizable(false);

        txtServerURL.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.txtServerURL.text")); // NOI18N
        txtServerURL.setToolTipText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.txtServerURL.toolTipText")); // NOI18N
        txtServerURL.setEnabled(false);

        bGoWMSHeight.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.bGoWMSHeight.text")); // NOI18N
        bGoWMSHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGoWMSHeightActionPerformed(evt);
            }
        });

        cbServerURL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "http://geoportal.wuppertal.de:8083/deegree/wms?", "http://serv-2118.kl.dfki.de:8888/geoserver/wms?service=WMS&version=1.1.0" }));

        lServerURL.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.lServerURL.text")); // NOI18N

        bgWMS.add(rbTxtServerUrl);
        rbTxtServerUrl.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.rbTxtServerUrl.text")); // NOI18N
        rbTxtServerUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTxtServerUrlActionPerformed(evt);
            }
        });

        bgWMS.add(rbCbServerUrl);
        rbCbServerUrl.setSelected(true);
        rbCbServerUrl.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.rbCbServerUrl.text")); // NOI18N
        rbCbServerUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCbServerUrlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pWMSHeightLayout = new javax.swing.GroupLayout(pWMSHeight);
        pWMSHeight.setLayout(pWMSHeightLayout);
        pWMSHeightLayout.setHorizontalGroup(
            pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWMSHeightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pWMSHeightLayout.createSequentialGroup()
                        .addGroup(pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pWMSHeightLayout.createSequentialGroup()
                                .addGroup(pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCbServerUrl)
                                    .addComponent(rbTxtServerUrl))
                                .addGap(10, 10, 10)
                                .addGroup(pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbServerURL, 0, 561, Short.MAX_VALUE)
                                    .addComponent(txtServerURL))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pWMSHeightLayout.createSequentialGroup()
                                .addComponent(pbWMS, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bGoWMSHeight)))
                        .addContainerGap())
                    .addGroup(pWMSHeightLayout.createSequentialGroup()
                        .addComponent(lServerURL)
                        .addContainerGap())))
        );
        pWMSHeightLayout.setVerticalGroup(
            pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWMSHeightLayout.createSequentialGroup()
                .addComponent(lServerURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbServerURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCbServerUrl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServerURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTxtServerUrl))
                .addGap(13, 13, 13)
                .addGroup(pWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bGoWMSHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbWMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pWMSHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pWMSHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("MainFrame.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        txtRequest.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.txtRequest.text")); // NOI18N
        txtRequest.setToolTipText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.txtRequest.toolTipText")); // NOI18N

        bGoWMSHeight1.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.bGoWMSHeight1.text")); // NOI18N
        bGoWMSHeight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGoWMSHeight1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(pbWMSLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bGoWMSHeight1)
                        .addGap(39, 39, 39))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bGoWMSHeight1)
                    .addComponent(pbWMSLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("MainFrame.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        cLayerList.setEnabled(false);
        cLayerList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cLayerListItemStateChanged(evt);
            }
        });

        lOpacity.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.lOpacity.text")); // NOI18N

        lHeight.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.lHeight.text")); // NOI18N

        txtHeight.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.txtHeight.text")); // NOI18N

        bAddWMSHeight.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.bAddWMSHeight.text")); // NOI18N
        bAddWMSHeight.setEnabled(false);
        bAddWMSHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddWMSHeightActionPerformed(evt);
            }
        });

        txtOpacity.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.txtOpacity.text")); // NOI18N

        bCancelWMSHeight.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.bCancelWMSHeight.text")); // NOI18N
        bCancelWMSHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelWMSHeightActionPerformed(evt);
            }
        });

        lMaxEle.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.lMaxEle.text")); // NOI18N

        javax.swing.GroupLayout dWMSHeightLayout = new javax.swing.GroupLayout(dWMSHeight.getContentPane());
        dWMSHeight.getContentPane().setLayout(dWMSHeightLayout);
        dWMSHeightLayout.setHorizontalGroup(
            dWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dWMSHeightLayout.createSequentialGroup()
                .addGroup(dWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dWMSHeightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(dWMSHeightLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dWMSHeightLayout.createSequentialGroup()
                                .addComponent(lHeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(319, 319, 319)
                                .addComponent(lOpacity)
                                .addGap(18, 18, 18)
                                .addComponent(txtOpacity, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dWMSHeightLayout.createSequentialGroup()
                                .addComponent(bCancelWMSHeight)
                                .addGap(90, 90, 90)
                                .addComponent(lMaxEle, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAddWMSHeight))
                            .addComponent(cLayerList, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dWMSHeightLayout.setVerticalGroup(
            dWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dWMSHeightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOpacity)
                    .addComponent(txtOpacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cLayerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dWMSHeightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddWMSHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelWMSHeight)
                    .addComponent(lMaxEle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("MainFrame.title")); // NOI18N

        pMain.setPreferredSize(new java.awt.Dimension(1200, 1024));

        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setLastDividerLocation(1);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        pLeftPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(pLeftPanel);

        pVisualization.setLayout(new java.awt.BorderLayout());

        pVisualization.add(wwPanel, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(pVisualization);

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        mFile.setText(bundle.getString("MainFrame.mFile.text")); // NOI18N

        miGotoLinz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        miGotoLinz.setText(bundle.getString("MainFrame.miGotoLinz.text")); // NOI18N
        miGotoLinz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGotoLinzActionPerformed(evt);
            }
        });
        mFile.add(miGotoLinz);

        miGotoPraque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miGotoPraque.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.miGotoPraque.text")); // NOI18N
        miGotoPraque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGotoPraqueActionPerformed(evt);
            }
        });
        mFile.add(miGotoPraque);

        miGoToStockhom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miGoToStockhom.setText(bundle.getString("MainFrame.miGoToStockhom.text")); // NOI18N
        miGoToStockhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGoToStockhomActionPerformed(evt);
            }
        });
        mFile.add(miGoToStockhom);

        miGotoWuppertal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        miGotoWuppertal.setText(bundle.getString("MainFrame.miGotoWuppertal.text")); // NOI18N
        miGotoWuppertal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGotoWuppertalActionPerformed(evt);
            }
        });
        mFile.add(miGotoWuppertal);
        mFile.add(jSeparator5);

        miFullSphere.setText(bundle.getString("MainFrame.miFullSphere.text")); // NOI18N
        miFullSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFullSphereActionPerformed(evt);
            }
        });
        mFile.add(miFullSphere);

        miGoto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        miGoto.setText(bundle.getString("MainFrame.miGoto.text")); // NOI18N
        miGoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGotoActionPerformed(evt);
            }
        });
        mFile.add(miGoto);
        mFile.add(jSeparator2);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        miExit.setText(bundle.getString("MainFrame.miExit.text")); // NOI18N
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        mbMain.add(mFile);

        mLayer.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.mLayer.text")); // NOI18N

        mAddLayer.setText(bundle.getString("MainFrame.mAddLayer.text")); // NOI18N

        miAddGeoTiff.setText(bundle.getString("MainFrame.miAddGeoTiff.text")); // NOI18N
        miAddGeoTiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddGeoTiffActionPerformed(evt);
            }
        });
        mAddLayer.add(miAddGeoTiff);
        mAddLayer.add(jSeparator6);

        miAddShape.setText(bundle.getString("MainFrame.miAddShape.text")); // NOI18N
        miAddShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddShapeActionPerformed(evt);
            }
        });
        mAddLayer.add(miAddShape);

        miAddShapeZip.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.miAddShapeZip.text")); // NOI18N
        miAddShapeZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddShapeZipActionPerformed(evt);
            }
        });
        mAddLayer.add(miAddShapeZip);
        mAddLayer.add(jSeparator4);

        miAddWMS.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.miAddWMS.text")); // NOI18N
        miAddWMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddWMSActionPerformed(evt);
            }
        });
        mAddLayer.add(miAddWMS);

        miAddWMSHeight.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.miAddWMSHeight.text")); // NOI18N
        miAddWMSHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddWMSHeightActionPerformed(evt);
            }
        });
        mAddLayer.add(miAddWMSHeight);

        mLayer.add(mAddLayer);

        miRemoveAllLayer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        miRemoveAllLayer.setText(bundle.getString("MainFrame.miRemoveAllLayer.text")); // NOI18N
        miRemoveAllLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoveAllLayerActionPerformed(evt);
            }
        });
        mLayer.add(miRemoveAllLayer);

        mbMain.add(mLayer);

        mWizard.setText(org.openide.util.NbBundle.getMessage(MainFrame.class, "MainFrame.mWizard.text")); // NOI18N

        miWizard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        miWizard.setText(bundle.getString("MainFrame.miWizard.text")); // NOI18N
        miWizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miWizardActionPerformed(evt);
            }
        });
        mWizard.add(miWizard);

        mbMain.add(mWizard);

        mHelp.setText(bundle.getString("MainFrame.mHelp.text")); // NOI18N

        miAbout.setText(bundle.getString("MainFrame.miAbout.text")); // NOI18N
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        mHelp.add(miAbout);

        mbMain.add(mHelp);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

    private void miGotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGotoActionPerformed
        dGoTo.setVisible(true);
    }//GEN-LAST:event_miGotoActionPerformed

    private void btnCancelGoToDialoagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelGoToDialoagActionPerformed
        dGoTo.setVisible(false);
    }//GEN-LAST:event_btnCancelGoToDialoagActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        try {
            double lat = Double.parseDouble(txtLatitude.getText());
            double lon = Double.parseDouble(txtLongitude.getText());
            wwPanel.setCamera(new SimpleCamera(lat, lon, 200000.0));
            dGoTo.setVisible(false);
        } catch (NumberFormatException nfe) {
            if (log.isWarnEnabled()) {
                log.warn("The content of the \"latitude\" and \"longitude\" "
                        + "component must be a double value.");
            }
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        JOptionPane.showMessageDialog(this, "This is the sudplan3D application."
                + "\nDFKI (c) 2011-2012",
                "About Sudplan3D",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miAboutActionPerformed

    private void miAddGeoTiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddGeoTiffActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("GeoTiff File ( *.tif, *.tiff)", "tif", "tiff"));

        int ret = fc.showOpenDialog(this);
        if (ret != JFileChooser.APPROVE_OPTION) {
            return;
        }

        wwPanel.addLayer(fc.getSelectedFile(), new VisCreateTexture(), null);
    }//GEN-LAST:event_miAddGeoTiffActionPerformed

    private void miAddShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddShapeActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("ESRI Shapefile (*.shp)", "shp"));

        int ret = fc.showOpenDialog(this);
        if (ret != JFileChooser.APPROVE_OPTION) {
            return;
        }

        IVisAlgorithm algo = VisAlgorithmFactory.newInstance(VisPointCloud.class.getName());
        if (algo != null) {
            wwPanel.addLayer(fc.getSelectedFile(), algo, null);
        } else {
            log.error("VisAlgorithm {} not supported.", VisPointCloud.class.getName());
        }
    }//GEN-LAST:event_miAddShapeActionPerformed

    private void miWizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miWizardActionPerformed
        wwPanel.runVisWiz();
    }//GEN-LAST:event_miWizardActionPerformed

    private void miRemoveAllLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoveAllLayerActionPerformed
        wwPanel.removeAllLayers();
    }//GEN-LAST:event_miRemoveAllLayerActionPerformed

    private void miGoToStockhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGoToStockhomActionPerformed
        wwPanel.setCamera(new AnimatedCamera(59.328, 18.047, 20000.0));
    }//GEN-LAST:event_miGoToStockhomActionPerformed

    private void miGotoLinzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGotoLinzActionPerformed
        wwPanel.setCamera(new AnimatedCamera(48.2323, 14.3350, 20000.0));
    }//GEN-LAST:event_miGotoLinzActionPerformed

    private void miGotoWuppertalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGotoWuppertalActionPerformed
        wwPanel.setCamera(new AnimatedCamera(51.249, 7.0832, 1510.0));
    }//GEN-LAST:event_miGotoWuppertalActionPerformed

    private void miFullSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFullSphereActionPerformed
        wwPanel.setCamera(new AnimatedCamera(37.0, 27.0, 19000000.0));
    }//GEN-LAST:event_miFullSphereActionPerformed

    private void miGotoPraqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGotoPraqueActionPerformed
        wwPanel.setCamera(new AnimatedCamera(50.08781, 14.42046, 20000.0));
    }//GEN-LAST:event_miGotoPraqueActionPerformed

    private void miAddShapeZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddShapeZipActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("ESRI Shapefile ZIP (*.zip)", "zip"));

        int ret = fc.showOpenDialog(this);
        if (ret != JFileChooser.APPROVE_OPTION) {
            return;
        }

        IVisAlgorithm algo = VisAlgorithmFactory.newInstance(VisPointCloud.class.getName());
        if (algo != null) {
            wwPanel.addLayer(fc.getSelectedFile(), algo, null);
        } else {
            log.error("VisAlgorithm {} not supported.", VisPointCloud.class.getName());
        }
    }//GEN-LAST:event_miAddShapeZipActionPerformed

    private void miAddWMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddWMSActionPerformed
        String s = JOptionPane.showInputDialog(this, "Add WMS", "Add WMS", JOptionPane.PLAIN_MESSAGE);
        wwPanel.addWMS(s);
    }//GEN-LAST:event_miAddWMSActionPerformed

    private void bGoWMSHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGoWMSHeightActionPerformed
        String urlString;
        if (rbCbServerUrl.isSelected()) {
            urlString = cbServerURL.getSelectedItem().toString();
        } else {
            urlString = txtServerURL.getText();
        }
        SwingWorker worker = new WMSDataRetriever(urlString);
        worker.execute();
    }//GEN-LAST:event_bGoWMSHeightActionPerformed

    private void bAddWMSHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddWMSHeightActionPerformed
        dWMSHeight.setVisible(false);
        SwingWorker worker = new WMSSurfaceLayerGenerator();
        worker.execute();
    }//GEN-LAST:event_bAddWMSHeightActionPerformed

    private void bCancelWMSHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelWMSHeightActionPerformed
        resetWMSHeightDialog();
    }//GEN-LAST:event_bCancelWMSHeightActionPerformed

    private void miAddWMSHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddWMSHeightActionPerformed
        resetWMSHeightDialog();
        dWMSHeight.setVisible(true);
        dWMSHeight.setModal(true);
    }//GEN-LAST:event_miAddWMSHeightActionPerformed

    private void rbCbServerUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCbServerUrlActionPerformed
        if (rbCbServerUrl.isSelected()) {
            cbServerURL.setEnabled(true);
            txtServerURL.setEnabled(false);
        } else {
            cbServerURL.setEnabled(false);
            txtServerURL.setEnabled(true);
        }
    }//GEN-LAST:event_rbCbServerUrlActionPerformed

    private void rbTxtServerUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTxtServerUrlActionPerformed
        if (rbTxtServerUrl.isSelected()) {
            txtServerURL.setEnabled(true);
            cbServerURL.setEnabled(false);
        } else {
            txtServerURL.setEnabled(false);
            cbServerURL.setEnabled(true);
        }
    }//GEN-LAST:event_rbTxtServerUrlActionPerformed

    private void cLayerListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cLayerListItemStateChanged
//        if (cLayerList.getItemCount() > 0) {
//            Globe globe = wwPanel.getWwd().getModel().getGlobe();
//            LayerInfo li = (LayerInfo) cLayerList.getSelectedItem();
//            lMaxEle.setText("Maximum elevation of selected layer = "
//                    + WMSHeightUtils.getMaxElevationOfSector(
//                    li.getLayerCapabilities().getGeographicBoundingBox(), globe));
//        }
    }//GEN-LAST:event_cLayerListItemStateChanged

    private void bGoWMSHeight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGoWMSHeight1ActionPerformed
        SwingWorker worker = new WMSLayerRetriever(txtRequest.getText());
        worker.execute();
    }//GEN-LAST:event_bGoWMSHeight1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;




                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddWMSHeight;
    private javax.swing.JButton bCancelWMSHeight;
    private javax.swing.JButton bGoWMSHeight;
    private javax.swing.JButton bGoWMSHeight1;
    private javax.swing.ButtonGroup bgWMS;
    private javax.swing.JButton btnCancelGoToDialoag;
    private javax.swing.JButton btnGo;
    private javax.swing.JComboBox cLayerList;
    private javax.swing.JComboBox cbServerURL;
    private javax.swing.JDialog dGoTo;
    private javax.swing.JDialog dWMSHeight;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JOptionPane jopAddServer;
    private javax.swing.JLabel lHeight;
    private javax.swing.JLabel lLatitude;
    private javax.swing.JLabel lLongitude;
    private javax.swing.JLabel lMaxEle;
    private javax.swing.JLabel lOpacity;
    private javax.swing.JLabel lServerURL;
    private javax.swing.JMenu mAddLayer;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenu mLayer;
    private javax.swing.JMenu mWizard;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miAddGeoTiff;
    private javax.swing.JMenuItem miAddShape;
    private javax.swing.JMenuItem miAddShapeZip;
    private javax.swing.JMenuItem miAddWMS;
    private javax.swing.JMenuItem miAddWMSHeight;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miFullSphere;
    private javax.swing.JMenuItem miGoToStockhom;
    private javax.swing.JMenuItem miGoto;
    private javax.swing.JMenuItem miGotoLinz;
    private javax.swing.JMenuItem miGotoPraque;
    private javax.swing.JMenuItem miGotoWuppertal;
    private javax.swing.JMenuItem miRemoveAllLayer;
    private javax.swing.JMenuItem miWizard;
    private javax.swing.JPanel pGoTo;
    private javax.swing.JPanel pLeftPanel;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pVisualization;
    private javax.swing.JPanel pWMSHeight;
    private javax.swing.JProgressBar pbWMS;
    private javax.swing.JProgressBar pbWMSLayer;
    private javax.swing.JRadioButton rbCbServerUrl;
    private javax.swing.JRadioButton rbTxtServerUrl;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtOpacity;
    private javax.swing.JTextField txtRequest;
    private javax.swing.JTextField txtServerURL;
    // End of variables declaration//GEN-END:variables

    /**
     * Resets the
     * <code>jDialog</code> WMSHeight.
     */
    private void resetWMSHeightDialog() {
        dWMSHeight.setVisible(false);
        txtServerURL.setText("http://serv-2118.kl.dfki.de:8888/geoserver/wms?service=WMS&version=1.1.0");
        txtServerURL.setEnabled(true);
        txtHeight.setText("200.0");
        txtHeight.setVisible(false);
        lHeight.setVisible(false);
        lOpacity.setVisible(false);
        txtOpacity.setVisible(false);
        bGoWMSHeight.setEnabled(true);
        bAddWMSHeight.setEnabled(false);
        cLayerList.setEnabled(false);
        txtServerURL.setEnabled(false);
        cbServerURL.setEnabled(true);
        pbWMS.setVisible(false);
        pbWMS.setIndeterminate(false);
        rbCbServerUrl.setSelected(true);
    }

    /**
     *
     */
    private class WMSLayerRetriever extends SwingWorker<LayerInfo, Void> {

        private String wmsURL;
        
        private WMSLayerRetriever() {
        }

        public WMSLayerRetriever(String wmsURL) {
            this.wmsURL = wmsURL;
        }

        @Override
        protected LayerInfo doInBackground() throws URISyntaxException, Exception {
            bGoWMSHeight1.setEnabled(false);
            return retrieveWMS(wmsURL);
        }

        private LayerInfo retrieveWMS(String wmsURL) throws URISyntaxException, Exception {
            pbWMSLayer.setIndeterminate(true);
            pbWMSLayer.setVisible(true);
            return WMSHeightUtils.parseWMSRequest(wmsURL);
        }

        @Override
        protected void done() {
            LayerInfo li = null;
            try {
                li = get();
            } catch (InterruptedException ex) {
                Exceptions.printStackTrace(ex);
            } catch (ExecutionException ex) {
                Exceptions.printStackTrace(ex);
            }
            if (li == null) {
                resetWMSHeightDialog();
                JOptionPane.showMessageDialog(dWMSHeight,
                        "Could not retreive WMS data from server.",
                        "WMS-Server Error",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                cLayerList.removeAllItems();
                cLayerList.addItem(li);
                bAddWMSHeight.setEnabled(true);
                pbWMSLayer.setIndeterminate(false);
                txtHeight.setVisible(true);
                txtOpacity.setVisible(true);
                lHeight.setVisible(true);
                lOpacity.setVisible(true);
                bGoWMSHeight1.setEnabled(true);
            }
        }
    }

    /**
     *
     */
    private class WMSDataRetriever extends SwingWorker<List<LayerInfo>, Void> {

        private WMSDataRetriever() {
        }

        public WMSDataRetriever(String wmsURL) {
            this.wmsURL = wmsURL;
            
        }

        @Override
        protected List<LayerInfo> doInBackground() throws URISyntaxException {
            bGoWMSHeight.setEnabled(false);
            return retrieveWMS(wmsURL);
        }

        private List<LayerInfo> retrieveWMS(String wmsURL) throws URISyntaxException {
            pbWMS.setIndeterminate(true);
            pbWMS.setVisible(true);
            URI serverURI = new URI(wmsURL.trim());
            return WMSHeightUtils.getLayerInfos(serverURI);
        }

        @Override
        protected void done() {
            pbWMS.setIndeterminate(false);
            List<LayerInfo> layerInfos = null;
            try {
                layerInfos = get();
            } catch (Exception ex) {
                log.error("Error: " + ex);
            }
            if (layerInfos == null) {
                resetWMSHeightDialog();
                JOptionPane.showMessageDialog(dWMSHeight,
                        "Could not retreive WMS data from server.",
                        "WMS-Server Error",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                cLayerList.removeAllItems();
                for (LayerInfo layerInfo : layerInfos) {
                    cLayerList.addItem(layerInfo);
                }
                cLayerList.setEnabled(true);
                bAddWMSHeight.setEnabled(true);
                txtHeight.setVisible(true);
                txtOpacity.setVisible(true);
                lHeight.setVisible(true);
                lOpacity.setVisible(true);
                bGoWMSHeight.setEnabled(true);
            }
        }
        private String wmsURL;
    }

    /**
     *
     */
    private class WMSSurfaceLayerGenerator extends SwingWorker<Boolean, Void> {

        @Override
        protected Boolean doInBackground() throws URISyntaxException {
            return generateLayer();
        }

        private Boolean generateLayer() throws URISyntaxException {
            LayerInfo layerInfo = (LayerInfo) cLayerList.getSelectedItem();
            double wmsHeight;
            double wmsOpacity;
            try {
                wmsHeight = Double.parseDouble(txtHeight.getText());
            } catch (NumberFormatException nfe) {
                if (log.isWarnEnabled()) {
                    log.warn("The content of the \"height\" "
                            + "component must be a double value.");
                }
                wmsHeight = 0.0;
                txtHeight.setText("0.0");
            }
            try {
                wmsOpacity = 1.0 - (Double.parseDouble(txtOpacity.getText()) / 100.0);
            } catch (NumberFormatException nfe) {
                if (log.isWarnEnabled()) {
                    log.warn("The content of the \"opacity\" "
                            + "component must be a double value between."
                            + "0.0 and 100.0 " + nfe);
                }
                wmsOpacity = 0.0;
                txtOpacity.setText("0.0");
            }
            if (wmsOpacity > 1.0 || wmsOpacity < 0.0) {
                log.warn("The content of the \"opacity\" "
                        + "component must be a double value between."
                        + "0.0 and 100.0");
                wmsOpacity = 0.0;
                txtOpacity.setText("0.0");
            }
            if (layerInfo == null) {
                log.error("Layer info is empty");
            } else {
//                LatLon location = WMSHeightUtils.getReferenceLocation(layerInfo.getLayerCapabilities().getGeographicBoundingBox());
//                wmsHeight -= globe.getElevation(location.getLatitude(), location.getLongitude());
//                log.debug("Elevation: "+wmsHeight);
                wwPanel.addWMSHeightLayer(layerInfo.getWMSCapabilities(), layerInfo.getLayerCapabilities(), layerInfo.getParameter(), wmsHeight, wmsOpacity);
            }
            return true;
        }

        @Override
        protected void done() {
            try {
                if (get()) {
                } else {
                }
            } catch (Exception ex) {
                log.error("Error: " + ex);
            }
        }
    }
}
