/*
 *  ParameterMappingPanel.java 
 *
 *  Created by DFKI AV on 01.01.2012.
 *  Copyright (c) 2011-2012 DFKI GmbH, Kaiserslautern. All rights reserved.
 *  Use is subject to license terms.
 */
package com.dfki.av.sudplan.vis.wiz;

import com.dfki.av.sudplan.vis.algorithm.IVisAlgorithm;
import com.dfki.av.sudplan.vis.algorithm.IVisParameter;
import java.util.Iterator;
import java.util.List;
import javax.swing.JPanel;

public final class ParameterMappingPanel extends JPanel {

    private IVisAlgorithm visAlgorithm;
    private String[] attributes;

    /**
     * Creates new form ParameterMappingPanel
     */
    public ParameterMappingPanel() {
        this.attributes = new String[]{};
        this.visAlgorithm = null;
        initComponents();
    }

    @Override
    public String getName() {
        return "Parameter Mapping";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ParameterMappingPanel.class, "ParameterMappingPanel.jLabel1.text")); // NOI18N
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @return 
     */
    public String[] getAttributes() {

        for (int i = 0, j = 0; i < this.getComponentCount(); i++) {
            if (getComponent(i) instanceof VisParameterPanel) {
                VisParameterPanel visParameterPanel = (VisParameterPanel) getComponent(i);
                attributes[j] = visParameterPanel.getSelectedAttribute();
                j++;
            }
        }
        return this.attributes;
    }
    
    /**
     * 
     * @param i
     * @param attributes 
     */
    public void setSelectedVisualization(IVisAlgorithm i, List<String> attributes) {
        this.visAlgorithm = i;
        this.attributes = new String[visAlgorithm.getVisParameters().size()];
        this.removeAll();
        
        if (visAlgorithm.getVisParameters().isEmpty()) {
            this.add(jLabel1);
        }
        
        for (Iterator<IVisParameter> it = visAlgorithm.getVisParameters().iterator(); it.hasNext();) {
            IVisParameter p = it.next();
            VisParameterPanel panel = new VisParameterPanel(p, attributes);
            this.add(panel);
        }
        
        this.updateUI();
    }
}
