/*
 *  VisParameterPanel.java 
 *
 *  Created by DFKI AV on 29.02.2012.
 *  Copyright (c) 2011-2012 DFKI GmbH, Kaiserslautern. All rights reserved.
 *  Use is subject to license terms.
 */
package com.dfki.av.sudplan.vis.wiz;

import com.dfki.av.sudplan.vis.algorithm.IVisParameter;
import com.dfki.av.sudplan.vis.algorithm.functions.ITransferFunction;
import com.dfki.av.sudplan.vis.wiz.tfpanels.TFPanel;
import com.dfki.av.sudplan.vis.wiz.tfpanels.TFPanelFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author steffen
 */
public class VisParameterPanel extends javax.swing.JPanel implements ActionListener {

    /*
     * Logger.
     */
    private static final Logger log = LoggerFactory.getLogger(VisParameterPanel.class);
    /**
     *
     */
    private IVisParameter visParameter;
    /**
     *
     */
    private Map<String, ITransferFunction> transferFunctionMap;
    /**
     *
     */
    private Map<String, TFPanel> panelMap;
    /**
     *
     */
    private String selectedTransferFunction;

    /**
     * Creates new form VisParameterPanel
     */
    public VisParameterPanel(final IVisParameter param, final List<String> dataAttributes) {
        this.visParameter = param;
        this.transferFunctionMap = new HashMap<String, ITransferFunction>();
        this.panelMap = new HashMap<String, TFPanel>();

        initComponents();

        //Create a panel for each available transfer function.
        List<ITransferFunction> list = param.getTransferFunctions();
        for (Iterator<ITransferFunction> it = list.iterator(); it.hasNext();) {
            ITransferFunction function = it.next();
            TFPanel panel = TFPanelFactory.get(function, dataAttributes, bgTransferFunctions, this);
            transferFunctionMap.put(function.getClass().getSimpleName(), function);
            panelMap.put(function.getClass().getSimpleName(), panel);
            this.add(panel);
            this.setTransferFunction(function);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTransferFunctions = new javax.swing.ButtonGroup();

        setAlignmentY(0.0F);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTransferFunctions;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public String getSelectedAttribute() {
        return panelMap.get(selectedTransferFunction).getSelectedAttribute();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        ITransferFunction f = transferFunctionMap.get(e.getActionCommand());
        setTransferFunction(f);
    }

    private void setTransferFunction(ITransferFunction f) {
        selectedTransferFunction = f.getClass().getSimpleName();
        visParameter.setSelectedTransferFunction(f);
        log.debug("Setting transfer function {} of VisParameter {} ", selectedTransferFunction, visParameter.getName());
    }
}
